<?php
/**
 * Plugin Name: {{PLUGIN_NAME}}
 * Description: Generated by PBS (schema_id={{SCHEMA_ID}}, schema_version={{SCHEMA_VERSION}})
 * Version: {{PLUGIN_VERSION}}
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

define('{{PLUGIN_FILE_CONST}}', __FILE__);
define('{{ID_CONST}}', {{PLUGIN_SLUG_PHP}});
define('{{PLUGIN_ID_CONST}}', {{PLUGIN_SLUG_PHP}});

spl_autoload_register(static function (string $class): void {
    $prefix = '{{GLIB_NS}}\\';
    if (!str_starts_with($class, $prefix)) {
        return;
    }
    $rel = substr($class, strlen($prefix));
    $rel = str_replace('\\', DIRECTORY_SEPARATOR, $rel);
    $path = __DIR__ . '/{{GLIB_NS}}/' . $rel . '.php';
    if (is_file($path)) {
        require_once $path;
    }
});

add_action('plugins_loaded', static function (): void {
    if (class_exists(\{{GLIB_NS}}\Init::class)) {
        \{{GLIB_NS}}\Init::register_services();
    }
});

